version: 2
jobs:
  mkdir:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: mkdir
          command: mkdir testdir
      - run:
          name: echo
          command: echo 'apa' > testdir/apa.txt
      - persist_to_workspace:
          root: testdir
          paths:
            - apa.txt
  ls:
    docker:
      - image: ubuntu
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/testdir
      - run:
          name: cat
          command: cat /tmp/testdir/apa.txt

workflows:
  version: 2
  mkdir_and_ls:
    jobs:
      - mkdir
      - ls:
          requires:
            - mkdir