version: 2
jobs:
  mkdir:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: mkdir
          command: mkdir patrik
  ls:
    docker:
      - image: ubuntu
    steps:
      - run:
          name: ls
          command: ls -l

workflows:
  version: 2
  mkdir_and_ls:
    jobs:
      - mkdir
      - ls