version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: mkdir
          command: mkdir patrik
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: ls
          command: ls -l
      