version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: pwd
          command: pwd
      - run:
          name: ls
          command: ls -la